# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: History of Arsenal Football Club | The Invincibles
email: hemdagem@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A history of all the famous moments for the Arsenal Football Club. A record 12 FA Cup wins. Going unbeaten in 2003/2004 which immortalised the club.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arsenalhistory.github.io" # the base hostname & protocol for your site

gems: [jekyll-paginate,jekyll-sitemap]
paginate: 8
paginate_path: "/page:num"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed

permalink: /:categories/:year/:permalink
