# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: History of Arsenal Football Club
email: hemdagem@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A history of all the famous moments for Arsenal Football Club.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arsenalhistory.github.io" # the base hostname & protocol for your site

gems: [jekyll-paginate]
paginate: 6
paginate_path: "/page:num"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
