name: Generate Arsenal Fixtures and Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

env:
  START_YEAR: 2024
  END_YEAR: 2025

jobs:
  generate-fixtures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install axios cheerio

      - name: Run Fixture Generation Script
        run: node generate-fixtures.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --staged --quiet || git commit -m "Update Arsenal fixtures for ${{ env.START_YEAR }}-${{ env.END_YEAR }}"
          git push
